### ISSUE TITLE
Enable stringification of map keys inside reports

### ISSUE THREAD

**Issue by felixeriksson** [ReVibe-Energy/pyanura#16]
Before merging #15 : Also stringify maps inside reports

See e-mail:

> Jag lyckades inte parsa snippet- och setting-rapporter med C++-biblioteket vi använder (nlohmann). Orsaken var att dessa innehåller datafält av typen "map[int, T]" vilket tyvärr inte stöds. Jag gjorde följande förändring i pyanura och det löste problemet. Iallafall för settings-rapporten men jag tror det också bör funka för snippet-rapporterna (kan testa på tisdag, den 26:e).

> diff --git a/anura/dataclasses_cbor.py b/anura/dataclasses_cbor.py
> index 9800019..f1bf302 100644
> --- a/anura/dataclasses_cbor.py
> +++ b/anura/dataclasses_cbor.py
> @ -24,9 +24,13 @@ def _make_default_encoder(string_keys=False):
>              for f in dataclasses.fields(inst):
>                  key = f.metadata.get("cbor_key", [f.name](http://f.name/))
>                  key = str(key) if string_keys else key
> \-                obj[key] = getattr(inst, [f.name](http://f.name/))
> \+                value = getattr(inst, [f.name](http://f.name/))
> \+                # Make sure dictionary values have string keys.
> \+                if string_keys and type(value) is dict:
> \+                    value = {str(k): v for k, v in value.items()}
> \+                obj[key] = value
>              encoder.encode(obj)
> \-    
> \+
>      return _default_encoder
>  
>  def _to_cbor(self, string_keys=False):

**Comment by rycee** [comment]
I think this can be closed with the merge of https://github.com/ReVibe-Energy/pyanura/commit/5f789a4e658aee1af0cb930e6046e29ce949bd96.
